version: '3.8'
name: patients-app

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres_db
    restart: always
    environment:
      POSTGRES_USER: patients
      POSTGRES_PASSWORD: password
      POSTGRES_DB: patients
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: